### ISSUE TITLE
rading grib returns error java.lang.NullPointerException

### ISSUE THREAD

**Issue by jbadag** [nctoolbox/nctoolbox#103]
When trying to read a GRIB file, I get the JAVA error: 

Error using ncdataset (line 97)
Failed to open C:

Error in cfdataset (line 59)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 74)
            obj = obj@cfdataset(url);

Error in bias_NCEP (line 11)
nc=ncgeodataset(archivo_con);

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.lang.NullPointerException

    	at ucar.nc2.grib.grib2.Grib2Rectilyser.cdmVariableHash(Grib2Rectilyser.java:453)

    	at ucar.nc2.grib.grib2.Grib2Rectilyser.make(Grib2Rectilyser.java:101)

    	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.makeAggregatedGroups(Grib2CollectionBuilder.java:489)

    	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.createIndex(Grib2CollectionBuilder.java:414)

    	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.readOrCreateIndex(Grib2CollectionBuilder.java:157)

    	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.readOrCreateIndexFromSingleFile(Grib2CollectionBuilder.java:77)

    	at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:123)

    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:310)

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

It works fine with others GRIBs files but with this gribs I can't read it. I attach an example grib file with which I have problems. I download it from the page http://apps.ecmwf.int/datasets/data/s2s-reforecasts-instantaneous-accum-kwbc/levtype=sfc/type=cf/

An example file with which I have problems can be downloaded from here: 
https://www.dropbox.com/s/j4mtsk0jsj2jiz2/20101229_31.grib?dl=0

Here is my code:

addpath C:\Users\badagianj\Desktop\nctoolbox-1.1.3
setup_nctoolbox
archivo_con='C:\Users\badagianj\Desktop\S2S\datos\reforecasts\NCEP\20101229_31.grib';
nc=ncgeodataset(archivo_con);
nc.variables 
lat=nc{'lat'}(1:end);
lon=nc{'lon'}(1:end);

My java version: 
version('-java')

ans =

    'Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode'

My matlab version is 2017a
Does anyone have an idea what could be causing the problem?

**Comment by hohonuuli** [comment]
Yep. I can confirm I get the same issue.

```
>> nc = ncdataset('/Users/brian/Downloads/20101229_31.grib')
2017-05-08 11:46:35,830 [main] WARN  ucar.nc2.grib.grib2.Grib2Pds  - Missing template 61
Error using ncdataset (line 97)
Failed to open /Users/brian/Downloads/20101229_31.grib

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.io.IOException: java.lang.NullPointerException
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:425)
    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:699)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:421)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:404)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:389)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:376)
    Caused by: java.lang.NullPointerException
    	at ucar.nc2.grib.grib2.Grib2Rectilyser.cdmVariableHash(Grib2Rectilyser.java:461)
    	at ucar.nc2.grib.grib2.Grib2Rectilyser.make(Grib2Rectilyser.java:113)
    	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.makeAggregatedGroups(Grib2CollectionBuilder.java:508)
    	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.createIndex(Grib2CollectionBuilder.java:434)
    	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.readOrCreateIndex(Grib2CollectionBuilder.java:148)
    	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.readOrCreateIndexFromSingleFile(Grib2CollectionBuilder.java:76)
    	at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:122)
    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:311)
    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1521)
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:813)
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:422)
    	... 5 more
```

**Comment by rsignell-usgs** [comment]
I tried opening this with the latest version of netcdf-java (4.6.10) and it can't open it either.   It's a netcdf-java issue, not directly a NCTOOLBOX issue.   I suggest you raise an issue on https://github.com/Unidata/thredds  (which covers both thredds and netcdf-java) and reference the issue here.
