### ISSUE TITLE
No records found in dataset, Unsupported GDS type = 12

### ISSUE THREAD

**Issue by cjwilliamson** [nctoolbox/nctoolbox#108]
### I'm having an issue reading grib files with the nctoolbox. Using a local grib file and the ncdataset function (nc = ncdataset('test2.grib')) on MATLAB 2016a on a Windows machine. The toolbox works perfectly when using nc files however, all the data (several thousand files) are in grib. Can anyone suggest a solution or a way to convert grib to nc that I can write into a MATLAB script? The grib file is from the Metoffice online dataset and works with xconv but I am trying to find a Windows solution. 
-------------------------------------------------------------------------------------------------------
```
Error using ncdataset (line 97)
Failed to open test2.grib

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.io.IOException: java.lang.IllegalStateException: No records found in dataset test2.grib

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:427)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:755)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:427)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:410)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:395)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:382)

    Caused by: java.lang.IllegalStateException: No records found in dataset test2.grib

    	at ucar.nc2.grib.collection.Grib2CollectionBuilder.makeGroups(Grib2CollectionBuilder.java:155)

    	at ucar.nc2.grib.collection.GribCollectionBuilder.createMultipleRuntimeCollections(GribCollectionBuilder.java:150)

    	at ucar.nc2.grib.collection.GribCollectionBuilder.createIndex(GribCollectionBuilder.java:138)

    	at ucar.nc2.grib.collection.GribCdmIndex.openGribCollectionFromDataFile(GribCdmIndex.java:780)

    	at ucar.nc2.grib.collection.GribCdmIndex.openGribCollectionFromDataFile(GribCdmIndex.java:764)

    	at ucar.nc2.grib.collection.GribCdmIndex.openGribCollectionFromRaf(GribCdmIndex.java:734)

    	at ucar.nc2.grib.collection.GribIosp.open(GribIosp.java:213)

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1560)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:835)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:424)

    	... 5 more

```

**Comment by rsignell-usgs** [comment]
@cjwilliamson, can you try loading that grib file in the latest version of Unidata's ToolsUI?

1. download
http://artifacts.unidata.ucar.edu/content/repositories/unidata-releases/edu/ucar/toolsUI/4.6.10/toolsUI-4.6.10.jar

2. open that .jar file with java , which brings up the ToolsUI GUI interface. 

3. Try to load your grib file.   

If it works, we should be able to make it work in Nctoolbox.   If it fails, it's an issue larger than Nctoolbox.

**Comment by cjwilliamson** [comment]
@rsignell-usgs Thanks for your quick response! 
I did try this in desperation last night and hadn't realized the implication! The file doesn't work with the ToolsUI either. 
Sorry, it's not a Nctoolbox issue. Can you recommend who to pass this on to? Would it be Thredds?
Thanks again!

**Comment by rsignell-usgs** [comment]
Yes, raise the issue with Unidata here https://github.com/Unidata/thredds/issues, though I'm afraid it's likely a metoffice issue.
