### ISSUE TITLE
have difficult in reading ECMWF grib2 file with nctoolBox

### ISSUE THREAD

**Issue by sbruceYoung** [nctoolbox/nctoolbox#110]
HI,
I want to read GRIB2 files using nctoolbox 1.1.3, but there is an error that I can't dissolve.  Can anyone give me some suggestions? one can find one small grib2 data file in attachment.
I read one issue on this board and found one similar error, but one expert have fix that bug in nctoolbox at 2014, and close that issue.
please help me..

any suggestion will be appreciate!

My system Info are follows;
OS : window 10 64bit
JAVA : Java 1.7.0
Matlab : R2014b
nctoolbox : nctoolbox-1.1.3
[ERA5_spec2d.ZIP](https://github.com/nctoolbox/nctoolbox/files/1341253/ERA5_spec2d.ZIP)

GRIB2 file : local files  ( download from ECMWF ERA5 analysis data, wave, 2D_Wave_Spectra(single) ).

**_Error message:_**

**_>> setup_nctoolbox
NCTOOLBOX added to Matlab path
>> nc=ncdataset('e:\ERA5_spec2d.grb');
>> Temp = nc.variables
Temp = 
    '2D_wave_spectra_single_msl'
    'lat'
    'lon'
    'time'
>> Lat = nc.data( 'lat' );
>> Lon = nc.data( 'lon' );
>> Spec2D = nc.data( '2D_wave_spectra_single_msl' );_**

Bitmap section length = 39408 != grid length 501000 (1000,501)Error using ncdataset/readdata (line 467)
Java exception occurred:
java.lang.IllegalStateException: Bitmap section length!= grid length %

	at ucar.nc2.grib.grib1.Grib1DataReader.getData(Grib1DataReader.java:176)

	at ucar.nc2.grib.grib1.Grib1Record.readData(Grib1Record.java:155)

	at ucar.nc2.grib.grib1.Grib1Record.readData(Grib1Record.java:175)

	at ucar.nc2.grib.grib1.Grib1Iosp$DataReader.read(Grib1Iosp.java:674)

	at ucar.nc2.grib.grib1.Grib1Iosp.readDataFromCollection(Grib1Iosp.java:637)

	at ucar.nc2.grib.grib1.Grib1Iosp.readData(Grib1Iosp.java:478)

	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:1941)

	at ucar.nc2.Variable.reallyRead(Variable.java:859)

	at ucar.nc2.Variable._read(Variable.java:831)

	at ucar.nc2.Variable.read(Variable.java:709)

	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:518)

	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:502)

	at ucar.nc2.Variable.read(Variable.java:709)

Error in ncdataset/data (line 165)
                    d = obj.readdata(variable);

**_Then I try to use command as
>> cdfInfo = nc.netcdf
 cdfInfo = 
netcdf e:/ERA5_spec2d.grb {
 dimensions:
   lon = 1000;
   lat = 501;
   time = 1;
 variables:
   float 2D_wave_spectra_single_msl(time=1, lat=501, lon=1000);
     :long_name = "2D wave spectra single @ Mean sea level";
     :units = "m2.s.radian-1";
     :missing_value = NaNf; // float
     :grid_mapping = "LatLon_Projection";
     :Grib_Variable_Id = "VAR_98-0-140-251_L102";
     :Grib1_Center = 98; // int
     :Grib1_Subcenter = 0; // int
     :Grib1_TableVersion = 140; // int
     :Grib1_Parameter = 251; // int
     :Grib1_Parameter_Name = "2DFD";
     :Grib1_Level_Type = 102; // int
   float lat(lat=501);
     :units = "degrees_north";
     :_CoordinateAxisType = "Lat";
   float lon(lon=1000);
     :units = "degrees_east";
     :_CoordinateAxisType = "Lon";
   int time(time=1);
     :units = "Hour since 2016-12-31T23:00:00Z";
     :standard_name = "time";
     :long_name = "product valid at RT + P1";
     :_CoordinateAxisType = "Time";

 :Originating_or_generating_Center = "European Centre for Medium Range Weather Forecasts (ECMWF) (RSMC)";
 :Originating_or_generating_Subcenter = "0";
 :Conventions = "CF-1.6";
 :history = "Read using CDM IOSP Grib1Collection";
 :featureType = "GRID";
 :file_format = "GRIB-1";
 :_CoordSysBuilder = "ucar.nc2.dataset.conv.CF1Convention";
}
>> bctd = nc.netcdf.getVariables().get(0)
 bctd = 
   float 2D_wave_spectra_single_msl(time=1, lat=501, lon=1000);
     :long_name = "2D wave spectra single @ Mean sea level";
     :units = "m2.s.radian-1";
     :missing_value = NaNf; // float
     :grid_mapping = "LatLon_Projection";
     :Grib_Variable_Id = "VAR_98-0-140-251_L102";
     :Grib1_Center = 98; // int
     :Grib1_Subcenter = 0; // int
     :Grib1_TableVersion = 140; // int
     :Grib1_Parameter = 251; // int
     :Grib1_Parameter_Name = "2DFD";
     :Grib1_Level_Type = 102; // int

>> Spec2D = bctd.read()

got same error information as following:
_**

Bitmap section length = 39408 != grid length 501000 (1000,501)Java exception occurred:
java.lang.IllegalStateException: Bitmap section length!= grid length %

	at ucar.nc2.grib.grib1.Grib1DataReader.getData(Grib1DataReader.java:176)

	at ucar.nc2.grib.grib1.Grib1Record.readData(Grib1Record.java:155)

	at ucar.nc2.grib.grib1.Grib1Record.readData(Grib1Record.java:175)

	at ucar.nc2.grib.grib1.Grib1Iosp$DataReader.read(Grib1Iosp.java:674)

	at ucar.nc2.grib.grib1.Grib1Iosp.readDataFromCollection(Grib1Iosp.java:637)

	at ucar.nc2.grib.grib1.Grib1Iosp.readData(Grib1Iosp.java:478)

	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:1941)

	at ucar.nc2.Variable.reallyRead(Variable.java:859)

	at ucar.nc2.Variable._read(Variable.java:831)

	at ucar.nc2.Variable.read(Variable.java:709)

	at ucar.nc2.dataset.VariableD

S.reallyRead(VariableDS.java:518)

	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:502)

	at ucar.nc2.Variable.read(Variable.java:709)

**Comment by hohonuuli** [comment]
I get the same errors when I try to open that file. I also tried with the latest version of the NetCDF-Java [toolsUI-4.6.10.jar](https://www.unidata.ucar.edu/downloads/netcdf/netcdf-java-4/index.jsp). __toolsUI__ throws an ArrayIndexOutOfBoundsException (see below). So there's either a bug in the Java GRIB library or there's something wrong with the GRIB file. Neither of which I can help you with. (Sorry):


When I try to access `2D_wave_spectra_single_msl` in the toolsUI, I get:

```
ava.lang.ArrayIndexOutOfBoundsException: 315258
	at ucar.nc2.grib.QuasiRegular.linear(QuasiRegular.java:276)
	at ucar.nc2.grib.QuasiRegular.convertQuasiGrid(QuasiRegular.java:151)
	at ucar.nc2.grib.grib1.Grib1Record.readData(Grib1Record.java:183)
	at ucar.nc2.grib.grib1.Grib1Record.readData(Grib1Record.java:167)
	at ucar.nc2.grib.grib1.Grib1Record.readData(Grib1Record.java:230)
	at ucar.nc2.grib.collection.Grib1Iosp.readData(Grib1Iosp.java:447)
	at ucar.nc2.grib.collection.GribIosp$DataReader.read(GribIosp.java:1096)
	at ucar.nc2.grib.collection.GribIosp.readDataFromCollection(GribIosp.java:1018)
	at ucar.nc2.grib.collection.GribIosp.readData(GribIosp.java:963)
	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2020)
	at ucar.nc2.Variable.reallyRead(Variable.java:874)
	at ucar.nc2.Variable._read(Variable.java:845)
	at ucar.nc2.Variable.read(Variable.java:723)
	at ucar.nc2.ui.VariablePlot.setVariable(VariablePlot.java:269)
	at ucar.nc2.ui.DatasetViewer.dataPlot(DatasetViewer.java:757)
	at ucar.nc2.ui.DatasetViewer.access$1400(DatasetViewer.java:78)
	at ucar.nc2.ui.DatasetViewer$NestedTable$6.actionPerformed(DatasetViewer.java:456)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
       ...
```

**Comment by sbruceYoung** [comment]
Many thanks to hohonuuli! 
I have test several **_ECMWF ERA5 analysis data file( wave, 2D_Wave_Spectra(single))_** , and can read its **_Test Data published by ECMWF_**, But Can't read its products. Its **_Test Data_** has different data organization with its products. its weird.
