### ISSUE TITLE
Warning: Escaped character '\U' is not valid. See 'doc sprintf' for supported special characters

### ISSUE THREAD

**Issue by roates1234** [nctoolbox/nctoolbox#117]
Anyone else receive this error using Windows 10 and Java version 1.8? 

I got it while trying to access a file:   ncdataset('C:\User\Documents\MATLAB\Temporary\file'). The full error message is below:

arning: Escaped character '\U' is not valid. See 'doc sprintf' for supported special
characters. 
> In ncdataset (line 89)
  In GFS_grab (line 150) 
Error using ncdataset (line 91)
Failed to open C:

Error in GFS_grab (line 150)
    tmpdata = ncdataset(outfilename);

Caused by:
    Error using ncdataset (line 75)
    Java exception occurred:
    java.io.IOException: java.lang.RuntimeException: java.lang.NoClassDefFoundError:
    ucar/nc2/util/CloseableIterator

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:425)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:699)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:421)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:404)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:389)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:376)

    Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError:
    ucar/nc2/util/CloseableIterator

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1557)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:813)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:422)

    	... 5 more

    Caused by: java.lang.NoClassDefFoundError: ucar/nc2/util/CloseableIterator

    	at
        ucar.nc2.grib.grib2.Grib2CollectionBuilder.<init>(Grib2CollectionBuilder.java:109)
        
    	at
        ucar.nc2.grib.grib2.Grib2CollectionBuilder.readOrCreateIndexFromSingleFile(Grib2CollectionBuilder.java:75)
        
    	at
        ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:122)

    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:311)

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1521)

    	... 7 more

    Caused by: java.lang.ClassNotFoundException: ucar.nc2.util.CloseableIterator

    	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)

    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    	... 12 more

 
>>

**Comment by yyyfool** [comment]
Same problem! 
My input file size was like only 200 M.
Got any solution?
