### ISSUE TITLE
1D vector problem

### ISSUE THREAD

**Issue by csherwood-usgs** [nctoolbox/nctoolbox#119]
Reading a vector from a .nc file generated by the COAWST version of ROMS (r. 1234). Using:

```
>> ver
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.4.0.813654 (R2018a)
MATLAB License Number: 188893
Operating System: Microsoft Windows 10 Enterprise Version 10.0 (Build 14393)
Java Version: Java 1.8.0_144-b01 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.4         (R2018a)
Image Processing Toolbox                              Version 10.2        (R2018a)
NCTOOLBOX Tools for read-only access to Common ...    Version 1.1.1-13-g8582810++ 
Parallel Computing Toolbox                            Version 6.12        (R2018a)
Signal Processing Toolbox                             Version 8.0         (R2018a)
Statistics and Machine Learning Toolbox               Version 11.3        (R2018a)
Wavelet Toolbox                                       Version 5.0         (R2018a)
```
This does not work:
`ws = nc{'Wsed'}(:)`

and returns this error:

```
>> ws = nc{'Wsed'}(:)
Error using ncdataset/readdata (line 491)
Java exception occurred:
ucar.ma2.InvalidRangeException: last (22) must be >= first (57)

	at ucar.ma2.Range.<init>(Range.java:146)

	at ucar.ma2.Range.<init>(Range.java:130)

Error in ncdataset/data (line 171)
                    d = obj.readdata(variable, first, last, stride);
Error in ncgeodataset/subsref (line 630)
                            B = builtin('subsref',obj,g);
Error in ncvariable/somedata (line 406)
                data = obj.dataset.data(name, first, last, stride);
Error in ncvariable/subsref (line 292)
                                        sref = obj.somedata(1, first, last, stride);
Error in ncgeodataset/subsref (line 660)
                        B = v.data(s(2).subs{:}); 
```

But this does, and returns a 1D vector:
`>> ws = nc{'Wsed'}(1)`
```
ws =
    0.0000
    0.0000
    0.0000
    0.0000
    0.0001
    0.0001
    0.0001
    0.0002
    0.0002
    0.0003
    0.0004
    0.0006
    0.0008
    0.0012
    0.0016
    0.0023
    0.0032
    0.0046
    0.0064
    0.0090
    0.0126
    0.0177
    0.0001
```

Here is a complete snippet of code that will generate the error:
```
clear
url='http://geoport.whoi.edu/thredds/dodsC/sand/usgs/users/aretxabaleta/floc/ocean_his_mor02_a35b05';
nc = ncgeodataset([url,'.nc'])

% These read correctly
Vtransform = nc{'Vtransform'}(:)
Vstretching = nc{'Vstretching'}(:)

% These all read correctly
s_rho = nc{'s_rho'}(:);
s_w = nc{'s_w'}(:);
Cs_r = nc{'Cs_r'}(:);
Cs_w = nc{'Cs_w'}(:);

% These read correctly
theta_s = nc{'theta_s'}(:)
theta_b = nc{'theta_b'}(:)
depth_c = nc{'hc'}(:)

% This does not. Nor does Wsed, Akv, or Akt
fdiam = 1e6*nc{'Sd50'}(1)
fdiam = 1e6*nc{'Sd50'}(:)
```

**Comment by Toby-D** [comment]
Hi Chris @csherwood-usgs! I realize this issue is 3 years old, but neat to see your name on here.

I ran into this issue. My conclusion is at least for some variables, ':' gets read as its ASCII code, 58. (See my comment on #91 ).
Java isn't my expertise, but it seems to be treating this syntax similar to if you used 'single(':')' in MATLAB.

In short, I don't think 
`lon=nc{'lon'}(:)`
should be used. Even when it works, it's starting at the 58th element in the dataset. As you indicated, 
'ws = nc{'Wsed'}(1)' should be used instead. 'readdata' will automatically calculate the end index as the size of the array in the respective dimension.

PS This is not limited to 1D variables. For certain 2D arrays, this occurs as well. In that case, people should use, e.g.
```
setup_nctoolbox 
url='http://www.smast.umassd.edu:8080/thredds/dodsC/fvcom/hindcasts/30yr_gom3';
nc=ncgeodataset(url);

lon=nc{'lon'}(1);
lat=nc{'lat'}(1);
%nv=nc{'nv'}(:).';
nv=nc{'nv'}([1 1])';
```
