### ISSUE TITLE
Trouble downloding data from ncei server

### ISSUE THREAD

**Issue by marcelo-hg** [nctoolbox/nctoolbox#120]
Hi everybody

I am trying to use nctoolbox to download NCEP reanalyses data from the ncei threadds data server (https://www.ncei.noaa.gov/thredds/catalog/cfs_reanl_ts/catalog.html). I can read the files, but I can't fetch any data. Here is the error that I keep getting:
```
opendap.dap.DAP2Exception: Method failed:HTTP/1.1 403 Forbidden
	at opendap.dap.DConnect2.openConnection(DConnect2.java:223)
	at opendap.dap.DConnect2.getData(DConnect2.java:699)
	at opendap.dap.DConnect2.getData(DConnect2.java:979)
	at ucar.nc2.dods.DODSNetcdfFile.readDataDDSfromServer(DODSNetcdfFile.java:1125)
	at ucar.nc2.dods.DODSNetcdfFile.readData(DODSNetcdfFile.java:1289)
	at ucar.nc2.Variable._read(Variable.java:978)
	at ucar.nc2.Variable.read(Variable.java:777)
	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:500)
	at ucar.nc2.Variable.read(Variable.java:777)
	at ucar.nc2.Variable.read(Variable.java:751)
Java exception occurred:
java.io.IOException: Method failed:HTTP/1.1 403 Forbidden

	at ucar.nc2.dods.DODSNetcdfFile.readData(DODSNetcdfFile.java:1296)

	at ucar.nc2.Variable._read(Variable.java:978)

	at ucar.nc2.Variable.read(Variable.java:777)

	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:500)

	at ucar.nc2.Variable.read(Variable.java:777)

	at ucar.nc2.Variable.read(Variable.java:751)
```

I contacted ncei support and they gave the following answer:

> The library may be getting tripped up by redirects that happen as the result of our HTTPS-only policy. Any HTTP request will redirect to the equivalent HTTPS page. The script is using 'http://' at the beginning of the URL, so changing that to 'https://' may help.  

That doesn't work...

> Another possible problem is that HTTPS connections can fail if the library that is doing the connection does not recognize the certificate used for our domain; this shouldn't be a problem with our production service, unless the library isn't properly set up to recognize SSL certificates.

I really don't know if the library is properly set up. I am trying to figure it out, but I appreciate any help.

I am using Matlab 2015a and the most recent nctoolbox version.

Thanks in advance.

My code:
```
clc;clear;close all;
setup_nctoolbox

ano=1979:2010;
mes=1:12;
dl='https://www.ncei.noaa.gov/thredds/dodsC/cfs_reanl_ts/';
arq='wnd10m.gdas.';
ext='.grb2';
%Extraction Points
rlat=-20;
rlon=-39.5;

for k=1:length(ano)
    for m=1:length(mes)
        st=[dl num2str(ano(k,1)) num2str(mes(m,1),'%02d') '/' arq num2str(ano(k,1)) num2str(mes(m,1),'%02d') ext];
        ds=ncdataset(st);
        lon=ds.data('lon');
        lat=ds.data('lat');
        %Locates the points
        lon(lon>180)=lon(lon>180)-360;
        lat=abs(lat-rlat);
        lon=abs(lon-rlon);
        [~,ilat]=min(lat);
        [~,ilon]=min(lon);
        
        ts=ds.size('time');
        ht=ds.time('time',1:ts(1));
        
        si=ds.size('u-component_of_wind_height_above_ground');
        hu=ds.data('u-component_of_wind_height_above_ground',[1 1 ilat ilon],[si(1) 1 ilat ilon]);
        hv=ds.data('v-component_of_wind_height_above_ground',[1 1 ilat ilon],[si(1) 1 ilat ilon]);
        
        if m==1
            gu=hu;
            gv=hv;
            gt=ht;
        else
            gu=[u;hu];
            gv=[v;hv];
            gt=[t,ht];
        end
        if k==1
            u=gu;
            v=gv;
            t=gt;
        else
            u=[u;gu];
            v=[v;gv];
            t=[t;tg];
        end
    end
end



```

**Comment by hohonuuli** [comment]
I ran a quick test. The data links they provide all start with `http` and those fail when you try to actually read the data. When I change the URLs to start with `https` they works for me. My tests are listed below:

### Fails with `http` prefix
```matlab
>> nc = ncdataset('http://www.ncei.noaa.gov/thredds/dodsC/cfs_reanl_ts/201008/wnd10m.gdas.201008.grb2');
>> t = nd.data('time');

opendap.dap.DAP2Exception: Method failed:HTTP/1.1 403 Forbidden on URL= http://www.ncei.noaa.gov/thredds/dodsC/cfs_reanl_ts/201008/z700.gdas.201008.grb2.dods?time[0:1:123][0:1:6]
	at opendap.dap.DConnect2.openConnection(DConnect2.java:271)
	at opendap.dap.DConnect2.getData(DConnect2.java:826)
	at opendap.dap.DConnect2.getData(DConnect2.java:1116)
	at ucar.nc2.dods.DODSNetcdfFile.readDataDDSfromServer(DODSNetcdfFile.java:1485)
        ....
```

### Works with `https` prefix

```
>> nc = ncdataset('https://www.ncei.noaa.gov/thredds/dodsC/cfs_reanl_ts/201008/wnd10m.gdas.201008.grb2');
>> t = nc.data('time');
>> size(t)

ans =

   124     7

```

**Comment by hohonuuli** [comment]
Actually ... I take that back. It worked with `time` but not with `u-component_of_wind_height_above_ground`. That's really confusing! In a nutshell, they're server configuration is __messed up__ (technical term). You can try the openDAP URL directly in your browser: https://www.ncei.noaa.gov/thredds/dodsC/cfs_reanl_ts/201008/wnd10m.gdas.201008.grb2.dods?u-component_of_wind_height_above_ground[0:1:123][0:1:6][0:1:0][0:1:575][0:1:1151] 

It returns a 403 (Forbidden) error:

```
Error {
    code = 403;
    message = "Request too big=2303.852544 Mbytes, max=500.0";
};
```

It looks like the request is asking for more data than their server is configured to deliver. You have 2 options: 1) Point it out to them and ask them to adjust the request limit on their server, 2) [download the file locally](https://www.mathworks.com/help/matlab/ref/websave.html) or 2) Fetch the data in chunks:

```
>> nc.size('u-component_of_wind_height_above_ground')

ans =

  1×5 int32 row vector

    124      7      1    576   1152

>> t = nc.data('u-component_of_wind_height_above_ground', [1 1 1 1 1], [124 7 1 1 1]);
```

Just a note that, I'm running tests on fetching by chunks and the server seems to respond really, really slowly.
