### ISSUE TITLE
Outdated JAVA 

### ISSUE THREAD

**Issue by MastUniv** [nctoolbox/nctoolbox#123]
I've been using NCTOOLBOX for a few months now and recently I can no longer read data from a URL. i.e. https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/WW3/Coastal_US_East_Coast/WW3_Coastal_US_East_Coast_2019XXXX_0000.grib2   where XXXX is Month (XX) and Day (XX), respectively.

Initially, I started getting a Protocol Version error since I was using MatLab 2016b I figured they updated to use a more recent version of JAVA. However, errors have persisted since upgrading the java version.  

I realize that this library hasn't been updated in like 3 years and maybe it never will be again but if someone is interested in taking a look at it let me know.  I have a little background in Java but nothing quite to this degree.  Find the most recent stack trace below, this is the result of my latest fix attempt in where I copied the cert from the website and added the bouncycastle jars to ext folder of java 8 that I installed and redirected Matlab to use:

javax.net.ssl.SSLException: Server key
	at sun.security.ssl.Handshaker.throwSSLException(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)
	at sun.security.ssl.AppOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)
	at ucar.nc2.util.net.HTTPMethod.execute(HTTPMethod.java:284)
	at ucar.nc2.dataset.NetcdfDataset.checkIfDods(NetcdfDataset.java:762)
	at ucar.nc2.dataset.NetcdfDataset.disambiguateHttp(NetcdfDataset.java:713)
	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:674)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)
Caused by: java.security.InvalidKeyException: No installed provider supports this key: sun.security.rsa.RSAPublicKeyImpl
	at java.security.Signature$Delegate.chooseProvider(Unknown Source)
	at java.security.Signature$Delegate.engineInitVerify(Unknown Source)
	at java.security.Signature.initVerify(Unknown Source)
	at sun.security.ssl.HandshakeMessage$DH_ServerKeyExchange.<init>(Unknown Source)
	... 25 more
Error using ncdataset (line 97)
Failed to open
https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/WW3/Global/WW3_Global_20191109_0000.grib2

Error in cfdataset (line 59)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 74)
            obj = obj@cfdataset(url);

Error in swhFromNetCdf_NOAA_OpenDAP_30day_NearCast_Single_Output_JBB (line 47)
nco=ncgeodataset(cell2mat(url(j)));

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    ucar.nc2.util.net.HTTPException: javax.net.ssl.SSLException: Server key

    	at ucar.nc2.util.net.HTTPMethod.execute(HTTPMethod.java:289)

    	at ucar.nc2.dataset.NetcdfDataset.checkIfDods(NetcdfDataset.java:762)

    	at ucar.nc2.dataset.NetcdfDataset.disambiguateHttp(NetcdfDataset.java:713)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:674)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

    Caused by: javax.net.ssl.SSLException: Server key

    	at sun.security.ssl.Handshaker.throwSSLException(Unknown Source)

    	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)

    	at sun.security.ssl.Handshaker.processLoop(Unknown Source)

    	at sun.security.ssl.Handshaker.process_record(Unknown Source)

    	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)

    	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)

    	at sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)

    	at sun.security.ssl.AppOutputStream.write(Unknown Source)

    	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)

    	at java.io.BufferedOutputStream.flush(Unknown Source)

    	at
        org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)

    	at
        org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
        
    	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)

    	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)

    	at
        org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)

    	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)

    	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)

    	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)

    	at ucar.nc2.util.net.HTTPMethod.execute(HTTPMethod.java:284)

    	... 7 more

    Caused by: java.security.InvalidKeyException: No installed provider supports this key:
    sun.security.rsa.RSAPublicKeyImpl

    	at java.security.Signature$Delegate.chooseProvider(Unknown Source)

    	at java.security.Signature$Delegate.engineInitVerify(Unknown Source)

    	at java.security.Signature.initVerify(Unknown Source)

    	at sun.security.ssl.HandshakeMessage$DH_ServerKeyExchange.<init>(Unknown Source)

    	... 25 more

Also, let me know if i'm barking up the wrong tree here too.  At this point, I don't really know what to do.  I think unidata had moved all the data over to https and NCTOOLBOX wasn't designed for it. There was an update to netcdf 4.3.15 -> netcdf 5.2.x, at least. 

Any feedback would be great. 

Cheers,

MastUniv

**Comment by hohonuuli** [comment]
@MastUniv I _think_ the thredds catalog you're accessing has been misconfigured. If you enter <https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/WW3/Coastal_US_East_Coast/WW3_Coastal_US_East_Coast_2019XXXX_0000.grib2> into a browser it's returning the following (I'm including the HTTP response headers here ... which the browser reads, but doesnt' display(

```
HTTP/1.1 400 400
Access-Control-Allow-Origin: *
Connection: close
Content-Description: dods-error
Content-Security-Policy: frame-ancestors 'self'
Content-Type: text/plain
Date: Mon, 09 Dec 2019 18:37:13 GMT
Server: Apache
Strict-Transport-Security: max-age=63072000; includeSubdomains;
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN

Error {
    code = 400;
    message = "Unrecognized request";
};
```

**Comment by hohonuuli** [comment]
I browsed to another GRIB file on their server and it appears to work fine:

```
>> n = ncdataset('https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20191112_1800.grib2')

n = 

  ncdataset with properties:

     location: 'https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20191112_1800.grib2'
       netcdf: [1×1 ucar.nc2.dataset.NetcdfDataset]
    variables: {55×1 cell}
```

**Comment by MastUniv** [comment]
Not that it will make much difference but did you change the XXXX part to reflect todays date i.e. 1209
It may be but I have spoke to someone at Thredds and they responded with this:

> "I believe this part of the stacktrace is key:

> Caused by: java.security.InvalidKeyException: No installed provider supports this key:
> sun.security.rsa.RSAPublicKeyImpl

That seems to indicate that the version of Java that matlab is using, or another library included with matlab, is unable to connect to our site using https. We've recently removed some older, insecure cryptographic protocols, which matlab may have been relying upon for secure communication. Note that we do not require any special keys, passwords, etc., and our certificate is issued by a widely use certificate authority. The issue seems to be purely associated with the java environment used by your installation of matlab.

> 

what version of Matlab are you using if you don't mind?  And, are you using the java it came with or newer version?

**Comment by hohonuuli** [comment]
> I realize that this library hasn't been updated in like 3 years and maybe it never will be again but if someone is interested in taking a look at it let me know. [...] There was an update to netcdf 4.3.15 -> netcdf 5.2.x, at least.

I would love to upgrade to a more recent netcdf version. Unfortunately, Matlab and netcdf have conflicting versions of [Apache HTTP libraries](https://hc.apache.org/). Matlab ships with a very outdated version (e.g. `/Applications/MATLAB_R2019b.app/java/jarext/axis2/httpcore.jar`) so I'm stonewalled from updating to a more recent Netcdf version.

**Comment by hohonuuli** [comment]
Also, just to summarize in case anyone comes across this thredd ... this issue is not related to the Java version.

**Comment by hohonuuli** [comment]
> Not that it will make much difference but did you change the XXXX part to reflect todays date i.e. 1209

```matlab
>> n = ncdataset('https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20191209_1800.grib2')
Error using ncdataset (line 97)
Failed to open
https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20191209_1800.grib2

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.io.IOException:
    https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20191209_1800.grib2
    is not a valid URL, return status=400
    	at ucar.nc2.dataset.NetcdfDataset.disambiguateHttp(NetcdfDataset.java:881)
    	at ucar.nc2.dataset.NetcdfDataset.disambiguateURL(NetcdfDataset.java:772)
    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:660)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:421)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:404)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:389)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:376)
```

``` http GET https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20191209_1800.grib2           (vars-localize)
HTTP/1.1 400 400
Access-Control-Allow-Origin: *
Connection: close
Content-Description: dods-error
Content-Security-Policy: frame-ancestors 'self'
Content-Type: text/plain
Date: Mon, 09 Dec 2019 18:59:35 GMT
Server: Apache
Strict-Transport-Security: max-age=63072000; includeSubdomains;
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN

Error {
    code = 400;
    message = "Unrecognized request";
};
```

**Comment by hohonuuli** [comment]
My Matlab version:

```
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.7.0.1190202 (R2019b)
MATLAB License Number: xxxxxxxxx
Operating System: Mac OS X  Version: 10.14.6 Build: 18G1012 
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.7         (R2019b)
Statistics and Machine Learning Toolbox               Version 11.6        (R2019b)
```

**Comment by MastUniv** [comment]
Hmmm... this is interesting.  The support staff at Thredds tried to say this was a java version issue, and given my initial error when attempting to access a different dataset this seemed to hold some water.

e.g. javax.net.ssl.SSLException: Received fatal alert: protocol_version
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)
	at sun.security.ssl.AppOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)
	at ucar.nc2.util.net.HTTPMethod.execute(HTTPMethod.java:284)
	at ucar.nc2.dataset.NetcdfDataset.checkIfDods(NetcdfDataset.java:762)
	at ucar.nc2.dataset.NetcdfDataset.disambiguateHttp(NetcdfDataset.java:713)
	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:674)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)
Error using ncdataset (line 97)
Failed to open
https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20191112_1800.grib2

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    ucar.nc2.util.net.HTTPException: javax.net.ssl.SSLException: Received fatal alert:
    protocol_version

    	at ucar.nc2.util.net.HTTPMethod.execute(HTTPMethod.java:289)

    	at ucar.nc2.dataset.NetcdfDataset.checkIfDods(NetcdfDataset.java:762)

    	at ucar.nc2.dataset.NetcdfDataset.disambiguateHttp(NetcdfDataset.java:713)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:674)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

    Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version

    	at sun.security.ssl.Alerts.getSSLException(Unknown Source)

    	at sun.security.ssl.Alerts.getSSLException(Unknown Source)

    	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)

    	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)

    	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)

    	at sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)

    	at sun.security.ssl.AppOutputStream.write(Unknown Source)

    	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)

    	at java.io.BufferedOutputStream.flush(Unknown Source)

    	at
        org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)
        
    	at
        org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
        
    	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)

    	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)

    	at
        org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
        
    	at
        org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)

    	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)

    	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)

    	at ucar.nc2.util.net.HTTPMethod.execute(HTTPMethod.java:284)

    	... 7 more

Actually, I may have mislead you. Because I didn't know when this would actually be seen, I only suggested that the date of the file be edited and not the time.  I don't think that this model i.e. https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/WW3/Coastal_US_East_Coast/WW3_Coastal_US_East_Coast_2019XXXX_1800.grib2  exists yet.  use 0000, 0600, 1200 instead of 1800. My first attempt to fix this was to download java 8 but then I just got a different error regarding DH size.

**Comment by hohonuuli** [comment]
Here's my attempt with date_time of 1209_1200:

```
>> n = ncdataset('https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20191209_1200.grib2')

n = 

  ncdataset with properties:

     location: 'https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20191209_1200.grib2'
       netcdf: [1×1 ucar.nc2.dataset.NetcdfDataset]
    variables: {55×1 cell}
```

>  The support staff at Thredds tried to say this was a java version issue

Actually, that _might_ be possible if you're running on Java 7 or earlier (Java < 7 uses TLSv1, the server could be running TLSv1.2). Java 7 reached it's end of life in April 2015.

**Comment by MastUniv** [comment]
But I tried updating to Java 8 which is what you're using and but that just changed the fatal error: Protocol Version to Fatal Error: DH size

**Comment by hohonuuli** [comment]
@MastUniv Can you run `ver` in Matlab, remove your license number, then posted it here so I can see your environment details?

**Comment by MastUniv** [comment]
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.1.0.441655 (R2016b)
MATLAB License Number: xxxxxxx
Operating System: Microsoft Windows 10 Pro for Workstations Version 10.0
(Build 18362)
Java Version: Java 1.8.0_231-b11 with Oracle Corporation Java HotSpot(TM)
64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.1
(R2016b)
