### ISSUE TITLE
Java Errors

### ISSUE THREAD

**Issue by Russ-Nas** [nctoolbox/nctoolbox#126]
It seems others are having similar issues so I thought I'd add my voice to the chorus. I did not use this code for a couple months and when I came back to it to run I get the following errors:
`Error using ncdataset (line 97)
Failed to open mhx_nwps_CG1_20200518_0000.grib2

Error in cfdataset (line 59)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 74)
            obj = obj@cfdataset(url);

Error in NSWP_download_create_v0_4 (line 49)
nco = ncgeodataset(fileName);

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.lang.RuntimeException: java.lang.NoClassDefFoundError: ucar/nc2/util/CloseableIterator

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1535)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

    Caused by: java.lang.NoClassDefFoundError: ucar/nc2/util/CloseableIterator

    	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.<init>(Grib2CollectionBuilder.java:115)

    	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.readOrCreateIndexFromSingleFile(Grib2CollectionBuilder.java:76)

    	at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:123)

    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:310)

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)

    	... 7 more

    Caused by: java.lang.ClassNotFoundException: ucar.nc2.util.CloseableIterator

    	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)

    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    	... 12 more`

I'm not sure if this is on my end and I updated something within Matlab so it's no longer compatible,   but it would be nice to have a solution! this is sort of the only way that I can access my GRIB files via MatLab. 
I am using the ftp.ncep.noaa.gov server to download the gribs and I can access them just fine, its opening them with netgeodataset that isn't seeming to work. 

This is the first issue i'm submitting on Git so I apologize if I am breaking any rules!

**Comment by hohonuuli** [comment]
It's helpful if you post a code sample that produces an error so that I can run a test.

**Comment by Russ-Nas** [comment]
Sorry if this is too much code, but I didnt want to exclude anything. The basic purpose of this code is to go to the FTP server, access the grip for that day (primarily the directory with the prefix 'ER'), download the data into a folder, and then access the data and create input files for a program called XBeach. 
The last portion is where the code is failing due to the NCToolBox Issues. Please let me know if I can be of any more help. 

ps. sorry if I am not following the best practices for this. Let me know if I've made an error and ill address it. 

`close all 
clc
% Info about netcdf file and ftp server
% region = er';
% variables = ['dp','hs','tp'];
% domain = 'CG1/';

prompt = 'Would you like to download data from the FTP server?: (Y/N)\n'
y_n = string(input(prompt,'s'));
if y_n == 'Y'
    % connect to ftp server
    ftpobj = ftp('ftp.ncep.noaa.gov');
    pasv(ftpobj);
    cd (ftpobj,'/pub/data/nccf/com/nwps/prod/');
    foreDate = dir(ftpobj);

    % pick a forecast date
    fn = {foreDate.name};
    [indx,tf] = listdlg('PromptString','Select a date:',...
                               'SelectionMode','single',...
                               'ListString',fn);
    myDate = foreDate(indx).name;
    fPath = ['/pub/data/nccf/com/nwps/prod/',myDate,'/mhx/'];
    cd(ftpobj,fPath);
    % Pick a forecast time
    foreTime = dir(ftpobj);
    fn = {foreTime.name};
    [indx,tf] = listdlg('PromptString','Select a time:',...
                               'SelectionMode','single',...
                               'ListString',fn);
    myTime = foreTime(indx).name;
    fPath = [myTime,'/CG1'];
    cd (ftpobj,fPath);
    % create a variable out of the grib file
    listing = dir(ftpobj);
    fileName = listing.name;
    % pick a folder
    mkdir 'NWPS_GRIB';
    gribDir = uigetdir;
    cd (gribDir);
    mget(ftpobj,fileName,fileName);
    cd (fileName);
    close(ftpobj);
    else
    [fileName,filePath] = uigetfile('.grib2','Select a GRIB file');
    cd (filePath);
end
% Variables from Grib2 File using NCTOOLBOX
nco = ncgeodataset(fileName);
nco.variables;
wavedir_param = 'Primary_wave_direction_degree_true_surface';
wavehei_param = 'Significant_height_of_combined_wind_waves_and_swell_surface';
waveper_param = 'Primary_wave_mean_period_surface';
wavesur_param = 'Deviation_of_sea_level_from_mean_surface';
wavetim_param = 'time';
% Store Lat/Lon points and time
lat = nco{'lat'}(:);
lon = nco{'lon'}(:);
time = nco{'time'}(:);

% change these coords to the 12 points along the coast
[coord_file,coord_path] = uigetfile('*.xlsx','Select coordinate file.');
if isequal(coord_file,0)
   disp('User selected Cancel');
else
   coord_fullpath = fullfile(coord_path,coord_file);
   disp(['User selected ', coord_fullpath]);
end
[coord,txt] = xlsread(coord_fullpath);
coord_sort = sortrows(coord,1,'ascend');

ex_lat = coord_sort(:,3);
ex_lon = coord_sort(:,2);
location_num = size(ex_lat,1);
i_lat = zeros(location_num,1);
i_lon = zeros(location_num,1);
% index matching area of interest through use of 'min' function
for j = 1:location_num
[m,i_la] = min(abs(lat-ex_lat(j)));
i_lat(j) = i_la;
[n,i_lo] = min(abs(lon-ex_lon(j)));
i_lon(j) = i_lo;
end

% Initialize array and store grib info in parameter variables
time_length = size(time,1);
waveparams_init = zeros(time_length,3);
surgeparams_init = zeros(time_length,2);

for i =  1:time_length
   i
   temp = nco{wavehei_param}(i,i_lat(1),i_lon(1));
   waveparams_init(i,2) = temp;
   temp = nco{wavetim_param}(i,i_lat(1),i_lon(1));
   surgeparams_init(i,1) = temp;
   temp = nco{wavesur_param}(i,i_lat(1),i_lon(1));
   surgeparams_init(i,2) = temp;
end

% pull 3 days around peak value
% check to see if this range of time is valid
plot(time,waveparams_init(:,2),'o')
hold
plot(time,surgeparams_init(:,2),'-')
hold
xticks(0:10:144)
grid on
grid minor
[t,h] = ginput(1);
close;
t = round(t);
t_range = [t-48 t t+48];
% check to see if t_range is great than max or less than zero
if t_range(1) <= 0
    t_range(1) = 1;
end
if t_range(3) > time_length
    t_range(3)= time_length;
end

% Create directories and surge.txt and jonswap.txt
timeDir = ([num2str(t_range(1)), '-', num2str(t_range(3))]);
mkdir (timeDir);

waveparams_m = zeros(73,3);
surgeparams_m = zeros(73,2);
grib_coord = zeros(location_num,2);
lineStyles = linspecer(location_num,'sequential'); % for later plots
for k = 1:location_num
    count = 1;
    for i = t_range(1):t_range(3)
    % update waveparams and surgeparams for the range selected
    temp = nco{wavehei_param}(i,i_lat(k),i_lon(k));
    waveparams_m(count,1) = temp;
    temp = nco{waveper_param}(i,i_lat(k),i_lon(k));
    waveparams_m(count,2) = temp;
    temp = nco{wavedir_param}(i,i_lat(k),i_lon(k));
    waveparams_m(count,3) = temp;
    temp = nco{wavetim_param}(i,i_lat(k),i_lon(k));
    surgeparams_m(count,1) = temp;
    temp = nco{wavesur_param}(i,i_lat(k),i_lon(k));
    surgeparams_m(count,2) = temp;
    count = count+1;
    grib_coord(k,:) = [lon(i_lon(k)), lat(i_lat(k))];
    % edit variable to length specified in t_range
    t_waveparams_m = waveparams_m.';
    t_surgeparams_m = surgeparams_m; %(t_range(1):t_range(3),:);
    % modify time so that  it is in seconds
    t_surgeparams_m(:,1) = ((t_surgeparams_m(:,1) - (t_range(1)-1))*3600);
    t_surgeparams_m = t_surgeparams_m.';
    % make jonswap and surge files
    cd (timeDir)
    jonswap_name = strcat('jonswap_',string(k),'.txt');
    surge_name = strcat('surge_',string(k),'.txt');
    [fid,msg] = fopen(jonswap_name,'wt');
    assert(fid>=3,msg);
    fprintf(fid, '%g %g %g 3.300 20.0000 3600 1\n', t_waveparams_m);
    fclose(fid);
    [fid,msg] = fopen(surge_name,'wt');
    assert(fid>=3,msg);
    fprintf(fid, '%g %g \n', t_surgeparams_m(:,:));
    fclose(fid);
    cd ..
    end
    % plot Jonswap for comparison
    X = t_range(1):t_range(3);
    y1 = waveparams_m(:,1);
    y2 = surgeparams_m(:,2);
    xlim1 = t_range(1)+20; xlim2 = t_range(3)-20;
    subplot(2,1,1);
    % top plot
    plot(X,y1 ,'DisplayName', string(k),'color',lineStyles(k,:))
    grid on
    grid minor
    xlim([xlim1 xlim2]);
    title('Significant Wave Height (m)');
    hold on
    % bottom plot
    subplot(2,1,2);
    plot(X,y2 ,'DisplayName', string(k),'color',lineStyles(k,:))
    grid on
    grid minor
    xlim([xlim1 xlim2]);
    title('Water Level (m)');
    hold on
    legend('-DynamicLegend', 'Interpreter', 'none')
end 
hold off
saveas(gcf,'Jonswap_Surge');
%Create a text file for xy coordinates of grib and store in grib folder. 
[X,Y] = ndgrid(lon,lat);
p = [X(:),Y(:)];
% Create a table with the data and variable names
T_Xy = table(p(:,1), p(:,2), 'VariableNames', { 'lon', 'lat'} );
% Write data to text file
writetable(T_Xy, 'grib_xy.txt');
grib_coord = double(grib_coord);
T_grib_coord = table(grib_coord(:,1), grib_coord(:,2), 'VariableNames', { 'lon', 'lat'} );
writetable(T_grib_coord, 'grib_coord_pulled.txt');
`

**Comment by hohonuuli** [comment]
@Russ-Nas Can you also post the issue you're running into?

**Comment by hohonuuli** [comment]
@Russ-Nas Never mind. I see it.

**Comment by TimMarlow** [comment]
Sorry to dig up an old issue, but did you find a solution?
Getting the same error. nctoolbox 1.1.3 , Matlab 2017b, Jave 1.8

Thanks

**Comment by AraZeph** [comment]
Was there a solution to this? I'm having the same problem

**Comment by ccalvosa** [comment]
Anyone know what is the solution? thx
