### ISSUE TITLE
Cannot open grib2 files in MATLAB R2020a

### ISSUE THREAD

**Issue by chro8062** [nctoolbox/nctoolbox#128]
I have been using nctoolbox for several months with great success, but I started running into issues when I switched to MATLAB R2020a. I am trying to read GFS data files downloaded from the ncep/noaa nomads cite using websave.m (https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/). The grib files are downloaded and stored locally because I need to run the code without internet connection. The following script runs correctly in MATLAB R2019a, but produces an error in MATLAB R2020a.

```
clear;
% print the current MATLAB version
ver

% Note that the dates in the url and file will need to be adjusted to grab currently available data
url = 'https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.20200601/18/';
file = 'gfs.t18z.pgrb2.0p25.f000';
localfile = websave(file,[url,file]);

% now open the grib data file whose name is localfile
addpath('./nctoolbox-1.1.3');
setup_nctoolbox;
ds = ncgeodataset(localfile)
```

Output for MATLAB R2019a:
```
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.6.0.1150989 (R2019a) Update 4
MATLAB License Number: xxxxxx
Operating System: Microsoft Windows 10 Home Version 10.0 (Build 18363)
Java Version: Java 1.8.0_181-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.6         (R2019a)
Simulink                                              Version 9.3         (R2019a)

NCTOOLBOX added to Matlab path

ds = 

  ncgeodataset with properties:

     location: 'C:\some\path\gfs.t18z.pgrb2.0p25.f000'
       netcdf: [1×1 ucar.nc2.dataset.NetcdfDataset]
    variables: {145×1 cell}
```

The output for MATLAB R2020a is this:

```
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.8.0.1359463 (R2020a) Update 1
MATLAB License Number: xxxxxx
Operating System: Microsoft Windows 10 Home Version 10.0 (Build 18363)
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.8         (R2020a)
Simulink                                              Version 10.1        (R2020a)

NCTOOLBOX added to Matlab path

Error using ncdataset (line 97)
Failed to open C:\some\path\gfs.t18z.pgrb2.0p25.f000

Error in cfdataset (line 59)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 74)
            obj = obj@cfdataset(url);

Error in nctoolbox_test (line 12)
ds = ncgeodataset(localfile)

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.lang.UnsupportedOperationException: This is
    supposed to be overridden by subclasses.

    	at
        com.google.protobuf.GeneratedMessage.getUnknownFields(GeneratedMessage.java:262)

    	at
        ucar.nc2.grib.grib2.Grib2IndexProto$GribGdsSection.getSerializedSize(Grib2IndexProto.java:944)

    	at
        com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:916)

    	at
        com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:668)

    	at
        ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index.getSerializedSize(Grib2IndexProto.java:2794)

    	at
        com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:70)

    	at
        ucar.nc2.grib.grib2.Grib2Index.makeIndex(Grib2Index.java:253)

    	at
        ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:112)

    	at
        ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:310)

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)

    	at
        ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)

    	at
        ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

    	at
        ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

    	at
        ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

    	at
        ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)
```

However, if the *.gbx9 and the *.ncx files already exist from that same grib file being opened with MATLAB R2019a, then MATLAB R2020a works just fine (the output is exactly the same as that shown above for R2019a). The problem seems to occur when MATLAB R2020a needs to produce the *.gbx9 and/or *.ncx files. I don't know if this is a JAVA problem.

The java version for MATLAB R2019a is:
```
>> version('-java')
ans =
    'Java 1.8.0_181-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode'
```

for MATLAB R2020a:
```
>> version('-java')
ans =
    'Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode'
```

Let me know if you need more information to help. Thanks!

**Comment by hohonuuli** [comment]
I was unable to duplicate your issue. I manually downloaded the file at <https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.20200603/18/gfs.t18z.pgrb2.0p25.f000> and ran the following, with no issues, in Matlab 2020a (Update 2):

```
>> n = ncgeodataset('/Users/brian/Downloads/gfs.t18z.pgrb2.0p25.f000')

n = 

  ncgeodataset with properties:

     location: '/Users/brian/Downloads/gfs.t18z.pgrb2.0p25.f000'
       netcdf: [1×1 ucar.nc2.dataset.NetcdfDataset]
    variables: {145×1 cell}
```

The error you're getting looks like its related to Google's protocol buffers:

```
java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses.
  at  com.google.protobuf.GeneratedMessage.getUnknownFields(GeneratedMessage.java:262)
```

One thing you can try is to go into `nctoolbox/java` and change rename the file `protobuf-java-2.6.1.jar` to `protobuf-java-2.6.1.jar.original` then restart Matlab and try again. This will remove nctoolbox's version of Google's protocol buffers, which might be conflictiing with a different version included with Matlab. Again, I'm guessing as I can't duplicate this. It's possible that Simulink includes a conflicting library (I'm not running Simulink)

**Comment by hohonuuli** [comment]
Also, do you get this with all those files at nomads or is this an intermittent problem?

**Comment by chro8062** [comment]
This problem does occur for all the GFS data files I have tried from nomads.

After looking into it a little more, I do think the problem comes from google's protocol buffers. In my 2020 MATLAB, there is a preinstalled version (protobuf3.jar) in MATLAB's static java path. There is not a preinstalled version on my MATLAB 2019. I also saw online that the same error I am seeing can occur if you mix classes that were compiled with different protobuf versions (https://github.com/protocolbuffers/protobuf/issues/1206#issuecomment-182586927). I had trimmed the MATLAB extensions I have in the original posts. I have the database toolbox installed on my 2020 Matlab, and I think that is where the pre-installed protobuf version comes from. I will reinstall MATLAB without that toolbox to see if the problem continues to occur and report back.

Thanks for the help!

**Comment by chro8062** [comment]
The problem does occur with every GFS file from nomads that I have tried.

So I looked into the protobuf jar file. I found that in my MATLAB 2020, a different version of protobuf is included in the static javaclasspath. Matlab 2019 does not have a version of protobuf already installed. So when I run nctoolbox in MATLAB 2020, it breaks because it is using the pre-installed protobuf rather than what comes with nctoolbox. I found a post on the protobuf page that says classes compiled with different versions of protobuf will result in the same error I am seeing (https://github.com/protocolbuffers/protobuf/issues/1206#issuecomment-182586927). For this same reason, chaning the name of the protobuf file in nctoolbox as suggested above does not fix the problem. 

So either I need to figure out how to install matlab without that preinstalled protobuf, or figure out a way to ensure the protobuf in nctoolbox is the one being called when I execute nctoolbox.

Thanks for the help so far!

**Comment by chro8062** [comment]
So after trying to reinstall MATLAB R2020a several different times (tried reinstalling with no toolboxes, tried clear all possible cached data from preinstallations, etc.), I still ran into the same error shown above. Each of time MATLAB was installed, it still included its own version of protobuf. So I went into the /java folder in the MATLAB install directory ( :\Program Files\MATLAB\R2020a\java) and manually removed the protobuf3.jar file that was in that directory, and now it works just fine. 

I do not really like this solution because I don't know what MATLAB uses protobuf for, and I don't always need to use NCTOOLBOX when I run MATLAB. So if MATLAB tries to access protobuf, it probably wont be able to find it.

What would it take to update nctoolbox to the newer protobuf version so that it doesn't conflict with a version MATLAB may have installed?
@hohonuuli Does your MATLAB 2020 have protobuf installed? (search for protobuf in the static javaclasspath: javaclasspath('-static'))
The pre-installed version of protobuf is in the static javaclasspath in matlab, which is always searched before the dynamic path (https://www.mathworks.com/help/matlab/matlab_external/java-class-path.html). How can I temporarily override/ignore the protobuf version preinstalled with some MATLAB versions?

Any thoughts/feedback would be great!

**Comment by 1gpranav** [comment]
Hi Everyone,

Just wanted to echo the issues that @chro8062 is having. I was wondering if anyone had figured out a way to get around deleting protobuf3.jar . I'm imagining there's a way to allow nctoolbox to reference the correct java file while its running but leave the MATLAB java files intact? Any advice on this would be appreciated!

**Comment by hohonuuli** [comment]
For a sanity check, try the suggestion I offered up earlier in this thread. Basically you disable nctoolboxes protobuf code.

> One thing you can try is to go into nctoolbox/java and change rename the file protobuf-java-2.6.1.jar to protobuf-java-2.6.1.jar.original then restart Matlab and try again.

If that doesn't fix anything, just change the name back to `protobuf-java-2.6.1.jar` to restore everything back to the way it was.I'd test it myself but I can't duplicate the issue.

**Comment by 1gpranav** [comment]
Hi @hohonuuli thanks for the response. Yes unfortunately even after following that step of changing the file name I encounter the same issue. The contents of the error message are the same as @chro8062 posted above ("Error using ncdataset (line 81) ...."

I'm using MATLAB 2020a and the same Java versions as posted above as well.

**Comment by chro8062** [comment]
@hohonuuli, I also disabled nctoolboxes protobuf code and got the same error. I assume it is because other things within nctoolbox are incompatible with the newer protobuf version?

@hohonuuli, does your MATLAB2020 have the protobuf3.jar file in the distribution files? It is in the following directory for me: C:\Program Files\MATLAB\R2020a\java\jarext

**Comment by hohonuuli** [comment]
Yep. `/Applications/MATLAB_R2020a.app/java/jarext/protobuf3.jar`

**Comment by chro8062** [comment]
I wonder if it is a problem just for Windows computers? If I get a chance, I will test it out on an ubuntu computer to see if it is still an issue.

**Comment by neilley** [comment]
Let me add some strange observations to this issue.  I am also having the same issue, and in my case its with grib1 files if that matters.   I'm running on Linux (CentOS7) and encourtered the same java errors shown above (   No problems with R2019b.  And here is the *really* strange observation that I just can't figure out....     If I run a script that uses nctoolbox under R2019b it runs just fine, and if I then immediately go into R2020a and run the same script, opening the same grib files it works (!), and continues to work fine for as many times I as I run it under R2020a for about 15-45 minutes.  Then it fails and will continue to fail until I run it again using R2019b.  Then the whole cycle can repeat.  Bizarre! This made me wonder if something about one of the various cache files matlab and java use might contain a clue as to why it works sometimes and not others.  But after looking through every file that changes in the user's home directories and below that changes between when it last successfully runs under R2020a, and when it fails under R2020a, I have not found any silver bullet there.  My guess there is some path caching someplace that allows the R2020a to run sucessfully using the last successful R2019b path/cache, but eventually that times out or is otherwise replaced.  It's very strange!

**Comment by neilley** [comment]
I meant to add that the workaround of removing (renaming) the matlab distributed version of the protobuf3.jar file works for me too on my linux instance.

**Comment by chro8062** [comment]
@neilley I also discovered that opening grib2 files in R2020a worked if they had already been opened by R2019a. I didn't observe the time dependency that you are talking about, but I am going to test that out today to see if it is true for me as well. When a grib2 file (those are the only ones I am working with, but I presume it is true for other files as well) is opened, 2 other files are created, a *.gbx9 file and a *.ncx file. When R2019a opens a grib2 file for the first time, it successfully creates those files. I found that R2020a can only open a grib2 file if both of those files have already been created. I get the above errors if either the *.gbx9 or the *.ncx files are not present.

**Comment by neilley** [comment]
@chro8062 yes, I think you are exactly correct.  If I delete those .gbx9 and .ncx files created by the R2019b run of the script, then run with R2020a it will always fail right away rather than 15+ minutes later.  So there must be some limit on how old those .gbx9 and .ncx files can be before nctoolbox will try to recreate them.

Anyway, the rename of the matlab version of the protobuf3.jar file workaround definitely "solves" the problem, but one has to wonder what other issues doing so creates someplace else.  It would be better if there was a way to remove that file from the javaclasspath (rather than renaming it), since that would enable users to just temporarily remove it while using nctoolbox.  But best I can tell, there is no way to remove a path from matlab's static java path.

**Comment by neilley** [comment]
The issue is indeed related to the protobuf(x).jar file shipped with MATLAB R2020a not being compatible with the version that nctoolbox uses.   There does not appear to be a way in matlab to temporarily change the order of static modules in the javapath so that when using nctoolbox matlab would find the version of protobuf shipped with nctoolbox first, and not the version shipped with R2020.  

The only workaround I've been able to come up with is the move the version of protobuf<x>.jar file shipped with Matlab out of the way, so nctoolbox finds its version of this .jar file first.  To accomplish this I just went to:
<matlab_install_folder>/java/jarext  and renamed protobuf3.jar to protobuf3.jar.save, restarted matlab, ran setup_nctoolbox, and all my grib(n) files were correctly being decoded by nctoolbox without error again.

Note: this solution may cause other problems elsewhere in matlab for any code that is dependent on protobuf3.jar.  So there may be derivative consequences of doing this (although I personally have not noticed any yet).  This is why I call this a "work around" and not a "solution".     The real solution might be to modify nctoolbox (or it's dependent code) to work with more recent versions of protobuf.jar.  But that would likely be too deep into the weeds for me.

**Comment by ajoros** [comment]
> 

I can say, this work around did work for me. Annoying that I have to resort to this but at least the project im working on doesnt require it to go in production.

**Comment by ajoros** [comment]
> The issue is indeed related to the protobuf(x).jar file shipped with MATLAB R2020a not being compatible with the version that nctoolbox uses. There does not appear to be a way in matlab to temporarily change the order of static modules in the javapath so that when using nctoolbox matlab would find the version of protobuf shipped with nctoolbox first, and not the version shipped with R2020.
> 
> The only workaround I've been able to come up with is the move the version of protobuf.jar file shipped with Matlab out of the way, so nctoolbox finds its version of this .jar file first. To accomplish this I just went to: <matlab_install_folder>/java/jarext and renamed protobuf3.jar to protobuf3.jar.save, restarted matlab, ran setup_nctoolbox, and all my grib(n) files were correctly being decoded by nctoolbox without error again.
> 
> Note: this solution may cause other problems elsewhere in matlab for any code that is dependent on protobuf3.jar. So there may be derivative consequences of doing this (although I personally have not noticed any yet). This is why I call this a "work around" and not a "solution". The real solution might be to modify nctoolbox (or it's dependent code) to work with more recent versions of protobuf.jar. But that would likely be too deep into the weeds for me.

I can say, this work around did work for me. Annoying that I have to resort to this but at least the project im working on doesnt require it to go in production.

**Comment by hohonuuli** [comment]
> Annoying that I have to resort to this

Yep. I agree. Matlab ships with a very large number of open source Java libraries. Unfortunately, some of these libraries are careless about making breaking API changes as they release new versions. When those changes clash with a library version used by NetCDF-Java, there's really not a lot I can do about it.  Protobuf is one, Apache Http Client is another that also causes huge headaches.
