### ISSUE TITLE
Failed to open GRIB-file

### ISSUE THREAD

**Issue by yoniv1** [nctoolbox/nctoolbox#129]
Hi,

I was trying to download some open source weather data from the COSMO weather model. I therefore use the following code:

```
clear all;
close all;
tic;

% Load nctoolbox

addpath('nctoolbox-1.1.3');
setup_nctoolbox;

startDate = datetime(date, 'ConvertFrom', 'yyyymmdd','TimeZone', 'UTC','Format', 'd MM yyyy');
myrun = 00;
myforecasthour = 24;

date_day = day(startDate)-1;
date_month = month(startDate);
date_year = year(startDate);

%% SNOW

fullURL1 = sprintf('https://opendata.dwd.de/weather/nwp/cosmo-d2/grib/%02d/snow_gsp/cosmo-d2_germany_regular-lat-lon_single-level_%4d%02d%02d%02d_%03d_SNOW_GSP.grib2.bz2',myrun,date_year,date_month,date_day,myrun,myforecasthour);
fullURL = [fullURL1];
filename = 'snow.grib2.bz2';
urlwrite(fullURL,filename);
cmd = sprintf("bzip2 -dk '%s'", filename);
system(cmd);
filename = 'snow.grib2';
grib = ncgeodataset(filename);
```

The last line yields the following error:

```
>> grib = ncgeodataset(filename);
Error using ncdataset (line 91)
Failed to open snow.grib2

Error in cfdataset (line 55)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 20)
            obj = obj@cfdataset(url);

Caused by:
    Error using ncdataset (line 75)
    Java exception occurred:
    java.io.IOException: java.lang.IllegalArgumentException: Attribute value cannot be null
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:425)
    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:699)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:421)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:404)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:389)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:376)
    Caused by: java.lang.IllegalArgumentException: Attribute value cannot be null
    	at ucar.nc2.Attribute.setStringValue(Attribute.java:508)
    	at ucar.nc2.Attribute.<init>(Attribute.java:370)
    	at ucar.nc2.grib.grib2.Grib2Iosp.addGroup(Grib2Iosp.java:568)
    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:335)
    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1521)
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:813)
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:422)
    	... 5 more

```

Can this problem be solved? When the link is changed to another weather model, it does work:

```
fullURL1 = sprintf('https://opendata.dwd.de/weather/nwp/icon-eu/grib/%02d/snow_gsp/icon-eu_europe_regular-lat-lon_single-level_%4d%02d%02d%02d_%03d_SNOW_GSP.grib2.bz2',myrun,date_year,date_month,date_day,myrun,myforecasthour);
```

What is wrong? Thanks!

**Comment by hohonuuli** [comment]
I tried to run your sample, but it's failing when constructing the `startDate`.

```
>> startDate = datetime(date, 'ConvertFrom', 'yyyymmdd','TimeZone', 'UTC','Format', 'd MM yyyy');
Error using datetime (line 586)
Input data must be one numeric matrix when converting from a different date/time representation.
```

Can you please post the full URL to a file that's causing the problem? Thanks

**Comment by yoniv1** [comment]
Hi,

Thanks for reacting! A full link for the file from the COSMO model that gives the error is as follows:

https://opendata.dwd.de/weather/nwp/cosmo-d2/grib/00/snow_gsp/cosmo-d2_germany_regular-lat-lon_single-level_2021012500_024_SNOW_GSP.grib2.bz2

When trying this link, with the ICON model, it should work with my code:

https://opendata.dwd.de/weather/nwp/icon-eu/grib/00/snow_gsp/icon-eu_europe_regular-lat-lon_single-level_2021012500_033_SNOW_GSP.grib2.bz2

I am not sure if they archive their data, maybe if you try this on a later date, you might need to change 20210125 to 20210126 according to the current date.

**Comment by yoniv1** [comment]
> I tried to run your sample, but it's failing when constructing the `startDate`.
> 
> ```
> >> startDate = datetime(date, 'ConvertFrom', 'yyyymmdd','TimeZone', 'UTC','Format', 'd MM yyyy');
> Error using datetime (line 586)
> Input data must be one numeric matrix when converting from a different date/time representation.
> ```
> 
> Can you please post the full URL to a file that's causing the problem? Thanks

**Comment by yoniv1** [comment]
> I tried to run your sample, but it's failing when constructing the `startDate`.
> 
> ```
> >> startDate = datetime(date, 'ConvertFrom', 'yyyymmdd','TimeZone', 'UTC','Format', 'd MM yyyy');
> Error using datetime (line 586)
> Input data must be one numeric matrix when converting from a different date/time representation.
> ```
> 
> Can you please post the full URL to a file that's causing the problem? Thanks

Does it work now?

**Comment by hohonuuli** [comment]
I get the same error you. Most likely, this is due to a bug in the version of the java grib library used in nctoolbox. Unfortunately, I can't upgrade to a more recent version due to a conflict between internal java dependencies in Matlab and Netcdf-Java.

**Comment by ComputerU** [comment]
I have this same problem. My Java version:
Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode.

Guessing there is no work around then?

**Comment by lrakmot** [comment]
Hi, I have also recently upgraded Matlab, and I am having a similar problem with Matlab R2020b   (9.9.0.1495850 (R2020b) Update 1) on a windows machine (W10). It was running fine on earlier Matlab releases e.g. R2018. I have tried the above fixes (e.g. deleting the .jar files or renaming them) – none works on my system. The NCTOOLBOX is able to read netcdf *.nc fine, but not *.grib2 files. There seems to be a problem with specifically parsing grib2 files. The code creates a *.gbx9 file from *.grib2, but then crashes. Would be great if there was a fix at one point or know what else to try. 

Java version: 'Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode'

best, Tom

Error code is posted below - Note that the Failed to open C: thomasrome_local - is not because it couldn't find the folder to begin with, but some parsing problem of the filename (perhaps from the *.gbx9) and possible filenamestructure -I can copy the 11h.grib2 file into the home/working directory of matlab and it would still not parse the grib2...with a similar error msg.

ds =     ncdataset('C:\0thomas\arome_local\uc\11h.grib2');
Warning: Escaped character '\u' is not valid. See 'doc sprintf' for
supported special characters. 
> In ncdataset (line 95) 
Error using ncdataset (line 97)
Failed to open C: thomasrome_local

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.io.IOException: java.lang.RuntimeException:
    java.lang.NoClassDefFoundError: ucar/nc2/util/CloseableIterator

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:425)

    	at
        ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:699)

    	at
        ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:421)

    	at
        ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:404)

    	at
        ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:389)

    	at
        ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:376)

    Caused by: java.lang.RuntimeException:
    java.lang.NoClassDefFoundError: ucar/nc2/util/CloseableIterator

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1557)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:813)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:422)

    	... 5 more

    Caused by: java.lang.NoClassDefFoundError:
    ucar/nc2/util/CloseableIterator

    	at
        ucar.nc2.grib.grib2.Grib2CollectionBuilder.<init>(Grib2CollectionBuilder.java:109)

    	at
        ucar.nc2.grib.grib2.Grib2CollectionBuilder.readOrCreateIndexFromSingleFile(Grib2CollectionBuilder.java:75)

    	at
        ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:122)

    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:311)

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1521)

    	... 7 more

    Caused by: java.lang.ClassNotFoundException:
    ucar.nc2.util.CloseableIterator

    	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)

    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    	... 12 more
