### ISSUE TITLE
Java Error while reading grib2 file

### ISSUE THREAD

**Issue by K9Amit** [nctoolbox/nctoolbox#137]
Hi,
I'm new to the grib format. I tried to install nctoolbox to Matlab 2023a. During the installation process, I got an error with the Java installation.
I followed suggestions online to comment the 6 row in the setup_nctoolbox_java.m file, and the package has been installed successfully.
But when I'm trying to load a grib2 file, I get the following error. I'm attaching the grib2 file, maybe it has something to do with the file itself?
Thanks!
Amit

Error using ncdataset
Failed to open C:/PhD/Radar/ADLP/MRMS/MRMS_PrecipRate_00.00_20230404-174000.grib2

Caused by:
    Error using ncdataset
    Java exception occurred:
    java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/jdom/JDOMException

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1535)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

    Caused by: java.lang.NoClassDefFoundError: org/jdom/JDOMException

    	at ucar.nc2.grib.grib2.table.Grib2Customizer.getTableValue(Grib2Customizer.java:155)

    	at ucar.nc2.grib.grib2.Grib2Iosp.addVerticalCoordinate(Grib2Iosp.java:625)

    	at ucar.nc2.grib.grib2.Grib2Iosp.addGroup(Grib2Iosp.java:463)

    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:334)

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)

    	... 7 more

    Caused by: java.lang.ClassNotFoundException: org.jdom.JDOMException

    	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

    	at com.mathworks.jmi.CustomURLClassLoader.findClass(ClassLoaderManager.java:760)

    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    	... 12 more
[MRMS_PrecipRate_00.00_20230404-174000.zip](https://github.com/nctoolbox/nctoolbox/files/11303163/MRMS_PrecipRate_00.00_20230404-174000.zip)

**Comment by nfpelak** [comment]
Hey Amit! I followed the same steps and am having a similar issue, also on R2023a (strangely, I was able to load the time, lat, and lon values, but not the data itself). Unfortunately I don't know how to solve it either, but following this in case someone does. 

One workaround that I found is to use the -netcdf option to the wgrib2 reader (https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/), which reads grib2 files and saves them as netcdf files, which can be opened in MATLAB. The main downside to this is that the netcdf files are much larger than the grib2 files.

**Comment by K9Amit** [comment]
Thanks!
Unfortunately, I also had problems using wgrib2. I guess that my computing skills are not so good.
However, I did succeed in installing pygrib package on Python. so I wrote a short script in Python that reads the grib2 file and transfer the data to Matlab.

**Comment by seismo2112** [comment]
Hi @K9Amit .

I am encountering same issue while reading file:
>>co = ncgeodataset(grib_directory);%, grib_file);
2023-06-15 15:10:06,981 [main] WARN  ucar.nc2.grib.grib2.Grib2Index  - Grib2Index bad size = -1 for /home/lalit/wavewatch3/gribfiles/multi_1.glo_30m.hs.201809.grb2 index = /home/lalit/wavewatch3/gribfiles/multi_1.glo_30m.hs.201809.grb2.gbx9
Error using ncdataset (line 97)
Failed to open
/home/lalit/wavewatch3/gribfiles/multi_1.glo_30m.hs.201809.grb2

Error in cfdataset (line 59)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 74)
            obj = obj@cfdataset(url);

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses.
    	at com.google.protobuf.GeneratedMessage.getUnknownFields(GeneratedMessage.java:262)
    	at ucar.nc2.grib.grib2.Grib2IndexProto$GribGdsSection.getSerializedSize(Grib2IndexProto.java:944)
    	at com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:877)
    	at com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:661)
    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index.getSerializedSize(Grib2IndexProto.java:2794)
    	at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:69)
    	at ucar.nc2.grib.grib2.Grib2Index.makeIndex(Grib2Index.java:253)
    	at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:112)
    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:310)
    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)
    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)
    	
    	>>
    	
    	
    	
    	I want to know how you transferred your data from python to MATLAB?

**Comment by K9Amit** [comment]
Hi, first of all, I will say I eventually used wgrib2. 
I'm attaching here a Matlab function (grib2mat.m) I wrote that you could use. I wrote this function for my needs, so you probably need to modify it, but it works.
The function reads a folder where the grib2 files are, uses wgrib2 to convert them into NetCDF format, then it uses Matlab's "ncinfo" and "ncread" to extract the data from the file. In my case, I just needed the lon/lat data and the radar data, but you can use "ncread" to extract whatever data you need from the grib2.
You do need to download the wgrib2 software and change row 24 in the code to the software path on your computer.

If you do want to use Python, I wrote a Python script (DataMRMS.py) that reads the grib file using pygrib. 
Then you can use this script in Matlab to run the Python script: (you need to change the bold parts)

 file_path = '**Path_to_grib_file**'
quoted_file_path = ['"' file_path '"' ]; % Enclose the file path in quotes
 sys = system(['python **Path_to_Python_script**\DataMRMS.py --file_path=' quoted_file_path]);

 % retrieve the values from the Python script
 py_data = py.DataMRMS.Values;

Again, you will need to change DataMRMS to retrieve the data you need from the grib file.

[grib_Codes.zip](https://github.com/nctoolbox/nctoolbox/files/11755995/grib_Codes.zip)

**Comment by seismo2112** [comment]
Yeah 
Actually, I converted my grib files to NC files and now I can use them using ncread. File size is not that much big.  I was thinking NCTOOL may help but wasted my time completely. They must update it on website. Python code is better and more accurate. [https://polar.ncep.noaa.gov/waves/examples/usingpython.shtml]
Thank you for your code. 
It might helpful to others in future. But wgrib2 is a key factor.
