### ISSUE TITLE
java error dowloading grb2 files

### ISSUE THREAD

**Issue by marisolosman** [nctoolbox/nctoolbox#76]
Hi,
I'm working with matlab 7.14.0.739 (R2012a) and java Java 1.6.0_17-b04 and I'm trying to download this, and others, grb2 files http://nomads.ncdc.noaa.gov/modeldata/cmd_mm_9mon/1981/198112/19811212/flxf1981121200.01.198201.avrg06Z.grb2
I get this error message
Error using ncdataset (line 91)
Failed to open
http://nomads.ncdc.noaa.gov/modeldata/cmd_mm_9mon/1981/198112/19811212/flxf1981121200.01.198201.avrg06Z.grb2

Error in cfdataset (line 55)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 20)
            obj = obj@cfdataset(url);

Caused by:
    Java exception occurred:
    ucar.nc2.util.net.HTTPException: java.net.NoRouteToHostException: No existe ninguna
    ruta hasta el «host»
    	at ucar.nc2.util.net.HTTPMethod.execute(HTTPMethod.java:289)
    	at ucar.nc2.dataset.NetcdfDataset.checkIfDods(NetcdfDataset.java:762)
    	at ucar.nc2.dataset.NetcdfDataset.disambiguateHttp(NetcdfDataset.java:713)
    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:674)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)
    Caused by: java.net.NoRouteToHostException: No existe ninguna ruta hasta el «host»
    	at java.net.PlainSocketImpl.socketConnect(Native Method)
    	at java.net.PlainSocketImpl.doConnect(Unknown Source)
    	at java.net.PlainSocketImpl.connectToAddress(Unknown Source)
    	at java.net.PlainSocketImpl.connect(Unknown Source)
    	at java.net.SocksSocketImpl.connect(Unknown Source)
    	at java.net.Socket.connect(Unknown Source)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at
        org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
            	at
        org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
            	at
        org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
    	at
        org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
            	at
        org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
            	at
        org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
            	at
        org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
    	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)
    	at ucar.nc2.util.net.HTTPMethod.execute(HTTPMethod.java:284)
    	... 7 more
 
I've looked other post but I couldn't find the solution. I though was a problem in the proxy configuration but when I changed the proxy and port I get the same error.
Any help will be appreciated

**Comment by hohonuuli** [comment]
I don't think that's a problem with nctoolbox. It looks like that's not a vaid URL. A[ java.net.NoRouteToHostException](https://docs.oracle.com/javase/8/docs/api/java/net/NoRouteToHostException.html) "Signals that an error occurred while attempting to connect a socket to a remote address and port. Typically, the remote host cannot be reached because of an intervening firewall, or if an intermediate router is down."

Also when I try to connect with that URL, I get a 404 (Not Found) exception (See below).:

```matlab
>> nc = ncdataset('http://nomads.ncdc.noaa.gov/modeldata/cmd_mm_9mon/1981/198112/19811212/flxf1981121200.01.198201.avrg06Z.grb2')
Error using ncdataset (line 97)
Failed to open
http://nomads.ncdc.noaa.gov/modeldata/cmd_mm_9mon/1981/198112/19811212/flxf1981121200.01.198201.avrg06Z.grb2

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.io.IOException:
    http://nomads.ncdc.noaa.gov/modeldata/cmd_mm_9mon/1981/198112/19811212/flxf1981121200.01.198201.avrg06Z.grb2
    is not a valid URL, return status=404

```

**Comment by marisolosman** [comment]
Thanks,
In that case, I don't know what else do because when I paste the same link in chrome I can download it correctly... and I need to work with most of those files
cheers

**Comment by hohonuuli** [comment]
You got me. Are you working with it on an internal network? Do you have your browser configured to use a proxy? When I try the link in a browser, I also get a 404 (Not Found) Error:


![apache_tomcat_6_0_20_-_error_report](https://cloud.githubusercontent.com/assets/282941/7529718/da5f45e0-f50a-11e4-874d-7d02d95f2ff4.png)

**Comment by marisolosman** [comment]
I', working using an internal network, but I also tried it at home, without proxy.

**Comment by grapesh** [comment]
@marisolosman
Your URL request is invalid; file name ends with *.avrg.06Z.grb2 instead of *.avrg06Z.grb2

**Comment by marisolosman** [comment]
Thanks, but when I tried a diferente file, like this one http://nomads.ncdc.noaa.gov/modeldata/cmd_mm_9mon/1985/198501/19850111/pgbf1985011112.01.198509.avrg.grb2, I can download it from my browser but not trough matlab
java.lang.System.setProperty('http.proxyHost','proxy.fcen.uba.ar');
java.lang.System.setProperty('http.proxyPort','8080');
setup_nctoolbox
setup_nctoolbox_java

url=('http://nomads.ncdc.noaa.gov/modeldata/cmd_mm_9mon/1985/198501/19850111/pgbf1985011112.01.198509.avrg.grb2');

a=ncgeodataset(url)

I get this message
Error using ncdataset (line 91)
Failed to open
http://nomads.ncdc.noaa.gov/modeldata/cmd_mm_9mon/1985/198501/19850111/pgbf1985011112.01.198509.avrg.grb2

Error in cfdataset (line 55)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 20)
            obj = obj@cfdataset(url);

Caused by:
    Java exception occurred:
    java.io.FileNotFoundException:
    http:/nomads.ncdc.noaa.gov/modeldata/cmd_mm_9mon/1985/198501/19850111/pgbf1985011112.01.198509.avrg.grb2
    (No existe el archivo o el directorio)
    	at java.io.RandomAccessFile.open(Native Method)
    	at java.io.RandomAccessFile.<init>(Unknown Source)
    	at java.io.RandomAccessFile.<init>(Unknown Source)
    	at ucar.unidata.io.RandomAccessFile.<init>(RandomAccessFile.java:277)
    	at ucar.unidata.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
    	at ucar.nc2.grib.grib2.Grib2Index.makeIndex(Grib2Index.java:234)
    	at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:112)
    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:310)
    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)
    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

**Comment by rsignell-usgs** [comment]
If I download this grib2 file and access it locally, it works okay with nctoolbox.  So it's just the remote http part that isn't working.   If I try to load this remote url using netcdf-java's tools-UI, I get the attached screen
![5-8-2015 9-24-16 am](https://cloud.githubusercontent.com/assets/1872600/7537141/62dc798e-f564-11e4-8b8f-51a1580637dc.png)

So it seems that netcdf-java thinks that the URL 
http://nomads.ncdc.noaa.gov/modeldata/cmd_mm_9mon/1985/198501/19850111/pgbf1985011112.01.198509.avrg.grb2
is a grib collection, not just a remote grib file. 

@cwardgar, any thoughts?

**Comment by rsignell-usgs** [comment]
Another option would be to see if this NCDC data is available via OPeNDAP, as that would be more efficient than remote http access.  

 @meteoman, I tried searching on "pgbf" and "tds", but didn't turn up any thredds access.   Do you know if this data exists on OPeNDAP?

**Comment by marisolosman** [comment]
Yeahhhhhhh I found an opendap link for that file and works!!
here is an example
 url='http://nomads.ncdc.noaa.gov/thredds/dodsC/modeldata/cmd_mm_9mon/1981/'

 dir=strcat(url,'198112/19811212/flxf1981121200.01.198112.avrg.00Z.grb2') 
ncgeodataset(dir)

ans = 

  ncgeodataset handle

  Properties:
     location: [1x123 char]
       netcdf: [1x1 ucar.nc2.dataset.NetcdfDataset]
    variables: {101x1 cell}

thank you!!!!!

**Comment by rsignell-usgs** [comment]
Excellent!
