### ISSUE TITLE
Reading GRIB2 file returns JAVA exception.

### ISSUE THREAD

**Issue by MrcJkb** [nctoolbox/nctoolbox#77]
Hello.

When trying to read a GRIB2 file, I get the JAVA error "Attribute value cannot be null".
It works fine with GRIB1 files containing the same type of data.
Does anyone have an idea what could be causing the problem?
For each data set there is one GRIB1 or GRIB2 file (depending on the date of creation)
containing the geographical data (rotated coordinates + projection) and a bunch of GRIB1/GRIB2
files containing the rest of the data (without the geographical data). I get the error on both types,
but only for the GRIB2 files.

Here is my code:

nc = ncgeodataset('filename');
Error using ncdataset (line 91)
Failed to open lfff00001500

Error in cfdataset (line 55)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 20)
            obj = obj@cfdataset(url);

Caused by:
    Error using ncdataset (line 75)
    Java exception occurred:
    java.lang.IllegalArgumentException: Attribute value
    cannot be null

    	at
        ucar.nc2.Attribute.setStringValue(Attribute.java:503)
        
    	at ucar.nc2.Attribute.<init>(Attribute.java:358)

    	at
        ucar.nc2.grib.grib2.Grib2Iosp.addGroup(Grib2Iosp.java:567)
        
    	at
        ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:334)
        
    	at
        ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)

    	at
        ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)
        
    	at
        ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
        
    	at
        ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
        
    	at
        ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
        
    	at
        ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

**Comment by acrosby** [comment]
Sorry this got missed, Is the URL an opendap endpoint? Can you post the examples that work and ones that don't?

Cheers,
Alex

**Comment by lakshaynarula** [comment]
Came across this issue today. I reverted back to version 1.1.0 and that seems to have solved the problem. Of course it'd be nice to have it working with the latest version too.
