### ISSUE TITLE
Unsupported DRS type = 50002

### ISSUE THREAD

**Issue by gtrem** [nctoolbox/nctoolbox#86]
Hello,

I am trying to read a .grib2 file containing several variables. The ncotoolbox works fine for 1 variable (which is temperature) but returns the following error for other variables (direct and diffuse downward solar radiation). Is the toolbox compatible with these variables  at this time ?

Thanks,

> Error using ucar.nc2.dataset.VariableDS/read
> Java exception occurred:
> java.lang.UnsupportedOperationException: Unsupported DRS type = 50002
> 	at ucar.nc2.grib.grib2.Grib2Drs.factory(Grib2Drs.java:59)
> 	at ucar.nc2.grib.grib2.Grib2SectionDataRepresentation.getDrs(Grib2SectionDataRepresentation.java:73)
> 	at ucar.nc2.grib.grib2.Grib2Record.readData(Grib2Record.java:282)
> 	at ucar.nc2.grib.grib2.Grib2Iosp$DataReader.read(Grib2Iosp.java:983)
> 	at ucar.nc2.grib.grib2.Grib2Iosp.readDataFromCollection(Grib2Iosp.java:912)
> 	at ucar.nc2.grib.grib2.Grib2Iosp.readData(Grib2Iosp.java:720)
> 	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:1957)
> 	at ucar.nc2.Variable.reallyRead(Variable.java:879)
> 	at ucar.nc2.Variable._read(Variable.java:865)
> 	at ucar.nc2.Variable.read(Variable.java:677)
> 	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:553)
> 	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:533)
> 	at ucar.nc2.Variable.read(Variable.java:677)
> 	at ucar.nc2.Variable.read(Variable.java:651)
> 
> Error in ncdataset/readdata (line 494)
>                 array = v.read(ranges);
> 
> Error in ncdataset/data (line 171)
>                     d = obj.readdata(variable, first, last, stride);
> 
> Error in ncgeodataset/subsref (line 630)
>                             B = builtin('subsref',obj,g);
> 
> Error in ncvariable/somedata (line 406)
>                 data = obj.dataset.data(name, first, last, stride);
> 
> Error in ncvariable/data (line 189)
>                 d = somedata(obj, 1, first, last, stride);
> 
> Error in ncgeovariable/subsref (line 1116)
>                                         sref = obj.data(first, last, stride);
> 
> Error in ncgeodataset/subsref (line 660)
>                         B = v.data(s(2).subs{:});

**Comment by rsignell-usgs** [comment]
@gtrem, nctoolbox uses the NetCDF-Java library to read GRIB files, so can you please do this test to find out if this is a generic netcdf-java problem or a NCTOOLBOX-specific problem?

Download ToolsUI from 
http://artifacts.unidata.ucar.edu/content/repositories/unidata-releases/edu/ucar/toolsUI/4.6.4/toolsUI-4.6.4.jar
open the jar with Java, and try opening your Grib file using the FeatureTypes=>Grid tab and trying to view the data variables.

Here's a video showing how to view grid variables in ToolsUI:  https://www.youtube.com/watch?v=GTFvdhlHivM

**Comment by gtrem** [comment]
Thank you @rsignell-usgs 

I can open the file with ToolsUI and visualize all variables. The variable name for temperature is ok. However, the variable names for the other parameters are not recognized.  I guess this prevent the NCTOOLBOX from reading the file. I attach some screenshots. Do you think I need to update the  NetCDF-Java Library?

![toolsui_gridviewer](https://cloud.githubusercontent.com/assets/17620326/13523385/7a43f128-e1f5-11e5-81ea-1ce452201160.png)
![toolsui_ncdump](https://cloud.githubusercontent.com/assets/17620326/13523386/7c3e8010-e1f5-11e5-8691-45c04c68fd49.png)
![toolsui_viewer](https://cloud.githubusercontent.com/assets/17620326/13523387/7df19370-e1f5-11e5-9338-8f6def0c1222.png)

**Comment by rsignell-usgs** [comment]
Try this test: 
Move the existing jar files in <nctoolbox>/java to some other directory temporarily (<nctoolbox> /orig_java or something) and then put the single Tools-UI.jar file in that folder instead. 

Then exit matlab, start it up, run setup_nctoolbox and then see if it reads your grib file variables.

**Comment by gtrem** [comment]
I tried it, but without success ...

> Error using ncdataset (line 97)
> Failed to open IEUfor_201512010000.grib2
> 
> Error in cfdataset (line 59)
>             obj = obj@ncdataset(url);
> 
> Error in ncgeodataset (line 74)
>             obj = obj@cfdataset(url);
> 
> Caused by:
>     Undefined variable "ucar" or class "ucar.nc2.dataset.NetcdfDataset.openDataset".

**Comment by BrianOBlanton** [comment]
?HI,  can you post or provide a url to the grib2 file??




<::><::><::><::><::><::><::><::>
Brian O. Blanton, Ph.D.
Oceanographer
Director of Environmental Initiatives
Renaissance Computing Institute
University of North Carolina at Chapel Hill
100 Europa Drive, Suite 540
Chapel Hill, NC, 27517

Brian_Blanton@Renci.Org
919-445-9620 (O)
919-445-9669 (F)
<::><::><::><::><::><::><::><::>
________________________________

**Comment by rsignell-usgs** [comment]
@gtrem , were you able to open other netcdf files in NCTOOLBOX using the updated ToolsUI.jar, just not the one that is giving you problems?

If nothing is opening, perhaps it didn't get installed right.
