### ISSUE TITLE
Error reading grib2 file

### ISSUE THREAD

**Issue by lianyuanz** [nctoolbox/nctoolbox#89]
Hi, Rich,

This is Lianyuan.  Today I downloaded the RTOFS girb2 file"rtofs_glo.t00z.n024_west_conus_std.grb2" from the weblink: ftp://ftpprd.ncep.noaa.gov/pub/data/nccf/com/rtofs/prod/rtofs.20160707/.  After I save the file on our Linux computer, on the MATLAB environment, I use command to open the grib2 file:
>> nc = ncgeodataset('rtofs_glo.t00z.n024_west_conus_std.grb2');

it shows the following error message:
 
**Error using ncdataset (line 91)
Failed to open /opt/ofsdev/users/zheng/code_develop/NC2GRIB/rtofs_glo.v1.0.7/rtofs_glo.t00z.n024_west_conus_std.grb2

Error in cfdataset (line 55)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 20)
            obj = obj@cfdataset(url);

Caused by:
    Error using ncdataset (line 75)
    Java exception occurred:
    java.io.IOException: java.lang.IllegalArgumentException: Attribute value cannot be null
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:425)
    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:699)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:421)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:404)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:389)
    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:376)
    Caused by: java.lang.IllegalArgumentException: Attribute value cannot be null
    	at ucar.nc2.Attribute.setStringValue(Attribute.java:508)
    	at ucar.nc2.Attribute.<init>(Attribute.java:370)
    	at ucar.nc2.grib.grib2.Grib2Iosp.addGroup(Grib2Iosp.java:568)
    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:335)
    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1521)
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:813)
    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:422)
    	... 5 more**

Does this mean that the this grib2 file can not be read by nctoolbox?  Please advice!

Thanks,
Lianyuan

**Comment by lakshaynarula** [comment]
Came across this issue today. I reverted back to version 1.1.0 and that seems to have solved the problem. Of course it'd be nice to have it working with the latest version too.

**Comment by rsignell-usgs** [comment]
Indeed, I've stuck with version 1.1.1 as newer versions seem to have problems.    It works fine here:
```
>> cd nctoolbox-1.1.1\
>> setup_nctoolbox
NCTOOLBOX added to Matlab path
>> cd downloads
>> url = 'rtofs_glo.t00z.f024_west_conus_std.grb2'

url =

rtofs_glo.t00z.f024_west_conus_std.grb2

>> nc = ncgeodataset(url)

nc = 

  ncgeodataset with properties:

     location: 'rtofs_glo.t00z.f024_west_conus_std.grb2'
       netcdf: [1x1 ucar.nc2.dataset.NetcdfDataset]
    variables: {11x1 cell}
```
@hohonuuli , should we revert back to this as the stable version?
I'm not sure what happened after 1.1.1.

**Comment by hohonuuli** [comment]
> I'm not sure what happened after 1.1.1

Looks like a lot of things changed ... unwinding that's going to be fun.

[diff-1.1.1_1.1.3.zip](https://github.com/nctoolbox/nctoolbox/files/711664/diff-1.1.1_1.1.3.zip)

**Comment by rsignell-usgs** [comment]
@drf5n, looks like mostly your contributions?
https://github.com/nctoolbox/nctoolbox/compare/1.1.1...1.0.x

**Comment by drf5n** [comment]
I think most of mine are documentation changes, except for:

https://github.com/nctoolbox/nctoolbox/commit/009f9bf17ac08b836c593c380b69045ad6de7daf

I think this was part of https://github.com/nctoolbox/nctoolbox/issues/65
