### ISSUE TITLE
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

### ISSUE THREAD

**Issue by mariuskist** [nctoolbox/nctoolbox#94]
Hello,

during the download of meteorological data from the CFSR database via OPeNDAP with nctoolbox an java error occured.

Running the code snippet:

"filepath = 'http://nomads.ncdc.noaa.gov/thredds/dodsC/modeldata/cmd_pgbh/2009/200910/20091028/pgbh01.gdas.2009102800.grb2'; 
ds=ncgeodataset(filepath);"

creates the error:

"javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)
	at sun.security.ssl.AppOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)
	at ucar.nc2.util.net.HTTPMethod.execute(HTTPMethod.java:284)
	at ucar.nc2.dataset.NetcdfDataset.checkIfDods(NetcdfDataset.java:762)
	at ucar.nc2.dataset.NetcdfDataset.disambiguateHttp(NetcdfDataset.java:713)
	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:674)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)
Error using ncdataset (line 91)
Failed to open
http://nomads.ncdc.noaa.gov/thredds/dodsC/modeldata/cmd_pgbh/2009/200910/20091028/pgbh01.gdas.2009102800.grb2

Error in cfdataset (line 55)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 20)
            obj = obj@cfdataset(url);

Caused by:
    Error using ncdataset (line 75)
    Java exception occurred:
    ucar.nc2.util.net.HTTPException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

    	at ucar.nc2.util.net.HTTPMethod.execute(HTTPMethod.java:289)

    	at ucar.nc2.dataset.NetcdfDataset.checkIfDods(NetcdfDataset.java:762)

    	at ucar.nc2.dataset.NetcdfDataset.disambiguateHttp(NetcdfDataset.java:713)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:674)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

    Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

    	at sun.security.ssl.InputRecord.handleUnknownRecord(Unknown Source)

    	at sun.security.ssl.InputRecord.read(Unknown Source)

    	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)

    	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)

    	at sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)

    	at sun.security.ssl.AppOutputStream.write(Unknown Source)

    	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)

    	at java.io.BufferedOutputStream.flush(Unknown Source)

    	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)

    	at
        org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
        
    	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)

    	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)

    	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)

    	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)

    	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)

    	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)

    	at ucar.nc2.util.net.HTTPMethod.execute(HTTPMethod.java:284)

    	... 7 more"

Trying the filepath in a browser is successfull.

Googeling, I find explanations which suggest that a java http method was used with a https url with the wrong port. 
I changed the port using setproxy() to 443 just in case with no success.
Anyway the tool did work like a charm in December since when no changes were made, and the OPeNDAP is extending the http protocol so I would not know where I should introduce a ssl connection anywhere or request a https connection in my code.

I use Matlab R2015b and nctoolbox version: nctoolbox-nctoolbox-20130305.

Do you have an idea about this behaviour ?
Best regards
Marius

**Comment by rsignell-usgs** [comment]
I just tried this with nctoolbox-1.1.1 and it worked fine:
```
>> cd nctoolbox-1.1.1\
>> setup_nctoolbox
NCTOOLBOX added to Matlab path
>> filepath = 'http://nomads.ncdc.noaa.gov/thredds/dodsC/modeldata/cmd_pgbh/2009/200910/20091028/pgbh01.gdas.2009102800.grb2';
ds=ncgeodataset(filepath)

ds = 

  ncgeodataset with properties:

     location: 'http://nomads.ncdc.noaa.gov/thredds/dodsC/modeldata/cmd_pgbh/2009/200910/20091028/pgbh01.gdas.20091028…'
       netcdf: [1x1 ucar.nc2.dataset.NetcdfDataset]
    variables: {190x1 cell}
```

**Comment by mariuskist** [comment]
Thank you for the fast reply.

I installed nctoolbox-1.1.1\ .

Unfortunatelly the error still occurs.

Formerly, I changed the setproxy file and use 
ucar.nc2.util.net.HTTPSession.setGlobalProxy(proxyname, port)
instead of 
ucar.nc2.util.net.HTTPSession.setGlobalSimpleProxy(proxyname, port)

Otherwise Matlab tells me that 
ucar.nc2.util.net.HTTPSession has no attribute called setGlobalSimpleProxy.

I don't think its the problem because that was no issue before, but could you confirm that ?

Best regards
Marius

**Comment by rsignell-usgs** [comment]
@mariuskist , I'm not sure what you want me to test.  Can you give me the explicit commands?
Otherwise, we could wait for @hohonuuli  to respond.

**Comment by mariuskist** [comment]
Sorry for the late reply, your last answer was swallowed by my spam filter.

My admin figured out: the problem is not on NOAA or the toolbox. 
Our proxy does strange things.
Using a part of our Network not routed over the proxy, the error does not occur.

I, therefore, close the issue.

Thanks for the immediate help.

Best regards
Marius
